In [1]:
import mysql.connector

In [18]:
mydb=mysql.connector.connect(host='localhost',user='root',password='King#123',database='pybase')

In [24]:
mycursor=mydb.cursor()
#mycursor.execute('create database pybase2')

In [31]:
mycursor.execute('create table customer1(cust_id int  primary key ,name varchar(255),address varchar(255))') 

In [32]:
mycursor.execute("insert into customer1 values(1,'abhishek','HP')")

In [34]:

mycursor.execute("insert into customer1 values(2,'sahil','UP')")
mycursor.execute("insert into customer1 values(3,'nishant','BIHAR')")
mycursor.execute("insert into customer1 values(4,'saurav','RAJASTHAN')")
mycursor.execute("insert into customer1 values(5,'manu','JK')")
mycursor.execute("insert into customer1 values(6,'vibhu','KERALA|')")

In [40]:

mycursor.fetchall()  # This will clear any unread results.

    

[(1, 'abhishek', 'HP'),
 (2, 'sahil', 'UP'),
 (3, 'nishant', 'BIHAR'),
 (4, 'saurav', 'RAJASTHAN'),
 (5, 'manu', 'JK'),
 (6, 'vibhu', 'KERALA|')]

In [41]:
mycursor.execute("select * from customer1")

In [42]:
for rows in mycursor.fetchall():
    print(rows)

(1, 'abhishek', 'HP')
(2, 'sahil', 'UP')
(3, 'nishant', 'BIHAR')
(4, 'saurav', 'RAJASTHAN')
(5, 'manu', 'JK')
(6, 'vibhu', 'KERALA|')


In [46]:
sql="insert into customer1(cust_id,name,address) values (%s,%s,%s)"
val=(10,'abhishek ahlawat','haryana')

mycursor.execute(sql,val)
mydb.commit()
print(mycursor.rowcount,"was inserted")

1 was inserted


In [47]:
mycursor.execute("select name,address from customer1")
for rows in mycursor.fetchall():
    print(rows)

('abhishek', 'HP')
('sahil', 'UP')
('nishant', 'BIHAR')
('saurav', 'RAJASTHAN')
('manu', 'JK')
('vibhu', 'KERALA|')
('abhishek ahlawat', 'haryana')


In [48]:
mycursor.execute("select name,address from customer1 limit 3")
for rows in mycursor.fetchall():
    print(rows)

('abhishek', 'HP')
('sahil', 'UP')
('nishant', 'BIHAR')


In [49]:
pip install numpy

11170.71s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [5]:
x=np.array([1,2,3,4])
y=np.array([[1,2],[3,4],[5,6]])


print('here is the value of x',x)
print('here is the value of y',y)

here is the value of x [1 2 3 4]
here is the value of y [[1 2]
 [3 4]
 [5 6]]


In [9]:
a1_zeros=np.zeros((3,3))
print(a1_zeros)
a1_range=np.arange(0,10,2)
print(a1_range)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
